site_name: GeneForgeLang (GFL)
site_description: 'The Symbolic Language for Biological Reasoning'
repo_url: https://github.com/Fundacion-de-Neurociencias/GeneForgeLang
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: blue
nav:
  - 'Home': index.md
  - 'Getting Started':
    - 'Installation': getting_started/installation.md
    - 'User Quickstart': getting_started/quickstart_user.md
  - 'Plugin Ecosystem':
    - 'Overview': ecosystem/plugins_overview.md
    - 'Core Plugins':
      - 'BLAST': ecosystem/core_plugins/blast.md
      - 'GATK': ecosystem/core_plugins/gatk.md
      - 'SAMtools': ecosystem/core_plugins/samtools.md
      - 'Biopython Tools': ecosystem/core_plugins/biopython.md
    - 'Genesis Plugins':
      - 'On-Target Scorer': ecosystem/genesis_plugins/ontarget_scorer.md
      - 'Off-Target Scorer': ecosystem/genesis_plugins/offtarget_scorer.md
      - 'CRISPR Evaluator': ecosystem/genesis_plugins/evaluator.md
      - 'CRISPR Visualizer': ecosystem/genesis_plugins/visualizer.md
  - 'For Developers':
    - 'Contributing': development/contributing.md
    - 'Creating a Plugin': development/creating_plugins.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Fundacion-de-Neurociencias/GeneForgeLang
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/geneforgelang/
