site_name: GeneForgeLang Documentation
site_description: Comprehensive documentation for GeneForgeLang - Domain-specific language for genomic workflows
site_author: Fundación de Neurociencias
site_url: https://fundacion-de-neurociencias.github.io/GeneForgeLang/

# Repository
repo_name: Fundacion-de-Neurociencias/GeneForgeLang
repo_url: https://github.com/Fundacion-de-Neurociencias/GeneForgeLang
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'


# Customization
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Fundacion-de-Neurociencias/GeneForgeLang
    - icon: fontawesome/solid/globe
      link: https://fundacion-neurociencias.org
  analytics:
    provider: google
    property: GOOGLE_ANALYTICS_KEY

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: Fundacion-de-Neurociencias
      repo: GeneForgeLang
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Tutorial: tutorial.md
    - CLI Tools: cli.md
  - Documentation:
    - Language Specification: gfl_yaml/SPECIFICATION.md
    - Examples: reasoning.md
    - Best Practices: Enhancer_Module_Spec.md
  - Web Platform:
    - Overview: WEB_API_IMPLEMENTATION_SUMMARY.md
  - API Reference:
    - REST API: API_REFERENCE.md
  - AI & Machine Learning:
    - Enhanced Inference: ENHANCED_INFERENCE_SUMMARY.md
  - Security:
    - Security Advisory: SECURITY_ADVISORY.md
  - Project:
    - Roadmap: PHASE_4_PLANNING.md
    - Documentation Guide: DOCUMENTATION_EXPORT_GUIDE.md
    - Deployment Guide: DEPLOYMENT_GUIDE.md
    - Contributing: ../CONTRIBUTING.md
    - Changelog: ../CHANGELOG.md
    - Citation: ../CITATION.cff

# Additional CSS
extra_css:
  - stylesheets/extra.css
