site_name: GeneForgeLang Documentation
site_description: Professional DSL for genomic workflows
site_url: https://geneforgelang.readthedocs.io
repo_url: https://github.com/Fundacion-de-Neurociencias/GeneForgeLang
repo_name: GeneForgeLang

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

nav:
  - Home: index.md
  - User Guide:
    - Installation: user-guide/installation.md
    - Quick Start: user-guide/quickstart.md
    - Workflow Syntax: user-guide/syntax.md
    - Examples: user-guide/examples.md
  - API Reference:
    - Core API: api/core.md
    - CLI Commands: api/cli.md
    - Plugin System: api/plugins.md
  - Architecture:
    - Overview: architecture/overview.md
    - Design Decisions: architecture/decisions.md
    - Plugin Development: architecture/plugins.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Fundacion-de-Neurociencias/GeneForgeLang
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/geneforgelang/
