[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "geneforgelang"
version = "0.2.3"

[project.optional-dependencies]
nl = ["transformers", "datasets", "torch"]

[tool.setuptools]
packages = ["gfl"]