[bu[project.scripts]rngfl-parse = "gfl.cli
"rngfl-validate = "gfl.cli
"rn["[project.scripts]rngfl-parse = "gfl.cli
"rngfl-validate = "gfl.cli
"rn[[project.scripts]rngfl-parse = "gfl.cli
"rngfl-validate = "gfl.cli
"rn[{nam[project.scripts]rngfl-parse = "gfl.cli
"rngfl-validate = "gfl.cli
"rn[
  "PyYAML>=6[project.scripts]rngfl-parse = "gfl.cli
"rngfl-validate = "gfl.cli
"rn[[project.scripts]rngfl-parse = "gfl.cli
"rngfl-validate = "gfl.cli
"rn["[project.scripts]rngfl-parse = "gfl.cli
"rngfl-validate = "gfl.cli
"rn["g[project.scripts]rngfl-parse = "gfl.cli
"rngfl-validate = "gfl.cli
"rn[
  "[project.scripts]rngfl-parse = "gfl.cli
"rngfl-validate = "gfl.cli
"rn[[project.scripts]rngfl-parse = "gfl.cli
"rngfl-validate = "gfl.cli
"rn["[project.scripts]rngfl-parse = "gfl.cli
"rngfl-validate = "gfl.cli
"rn["gfl*", "gf*"]

[[project.scripts]rngfl-parse = "gfl.cli
"rngfl-validate = "gfl.cli
"rn
