version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - ~/.gitconfig:/home/vscode/.gitconfig:ro
    environment:
      - PYTHONPATH=/workspace
    command: sleep infinity
    ports:
      - "8000:8000"
      - "8080:8080"
    networks:
      - gfl-network

  # Optional: Database service for testing
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: gfl_test
      POSTGRES_USER: gfl_user
      POSTGRES_PASSWORD: gfl_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - gfl-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gfl_user -d gfl_test"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:

networks:
  gfl-network:
    driver: bridge
